<h1>Konto użytkownika {$user->login}</h1>
<table class="table">
  <tr>
    <th>Login</th>
    <td>{$user->login}</td>
  </tr>
  <tr>
    <th>E-mail</th>
    <td>{$user->email}</td>
  </tr>
  <tr>
    <th>Imie</th>
    <td>{$entity->imie}</td>
  </tr>
  <tr>
    <th>Nazwisko</th>
    <td>{$entity->nazwisko}</td>
  </tr>
  {if isset($entity->id_klasy)}
  <tr>
    <th>PESEL</th>
    <td>{$entity->pesel}</td>
  </tr>
  {/if}
</table>
