<!DOCTYPE html>
<html lang="pl" dir="ltr">
  <head>
    <meta charset="utf-8">
    {if $title}
      <title>{$title}</title>
    {/if}
  </head>
  <body class="controller-{$controller}">
      {if $header}
        {$header|noescape}
      {/if}
    <div id="wrapper">
      {$output|noescape}
    </div>
    {foreach $jsFiles as $jsFile}
    <script src="{$jsFile}" charset="utf-8"></script>
    {/foreach}
  </body>
</html>
