<footer>
  <div class="inner">
    <div class="wrapper">
      
      <div class="powered">
        <div class="wrap">
          <div class="icon">
            <img src="src/styles/assets/github.svg" alt="git" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/php.svg" alt="php" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/sass.svg" alt="sass" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/mysql.svg" alt="sql" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/nette-logo.png" alt="nette" class="icon">
          </div>
        </div>
      </div>
      <div class="copyright">
        &copy;Copyright<br>
        Krzysztof&amp;Krzysztof
      </div>
    </div>
  </div>

</footer>
