<footer>
  <div class="inner">
    <div class="wrapper">

      <div class="powered">
        <div class="wrap">
          <div class="icon">
            <img src="src/styles/assets/github.svg" alt="git" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/php.svg" alt="php" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/sass.svg" alt="sass" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/mysql.svg" alt="sql" class="icon">
          </div>
          <div class="icon">
            <img src="src/styles/assets/nette-logo.png" alt="nette" class="icon">
          </div>
        </div>
      </div>
      <div class="copyright">
        &copy;Copyright 2019<br>
      </div>
      <div class="social">
        <div class="wrap">
          <div class="icon">
            <div class="circle">
              <img src="src/styles/assets/twitter.svg" alt="twitter" class="icon">
            </div>
            <div class="icon">
              <div class="circle">
                <img src="src/styles/assets/googleplus.svg" alt="twitter" class="icon">
              </div>
            </div>
            <div class="icon">
              <div class="circle">
                <img src="src/styles/assets/facebook.svg" alt="twitter" class="icon">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</footer>
