<header>
	<div class="inner">
		<a href="?">
			<h1>Bobidziennik</h1>
		</a>
		<nav id="mainNav">
			<ul>
				<li>
					<a href="#">
						Opcja 1
					</a>
				</li>
				<li>
					<a href="#">
						Opcja 2
					</a>
				</li>
				<li>
					<a href="#">
						Opcja 3
					</a>
				</li>
				<li>
					<a href="#">
						Opcja 4
					</a>
				</li>
				<li>
					<a href="#">
						Opcja 5
					</a>
				</li>
			</ul>
		</nav>
		<nav id="secondaryNav">
			<ul>
				<li>
					<a href="?s=logout">
						Wyloguj
					</a>
				</li>
			</ul>
		</nav>
	</div>
</header>
