<header>
    <div class="inner">
        <a href="?">
            <h1>Bobidziennik</h1>
        </a>
        <nav id="mainNav">
            <ul>
                <li>
                    <a href="?">
                        Strona główna
                    </a>
                </li>
                <li>
                    <a href="?s=timetable">
                        Plan lekcji
                    </a>
                </li>
                <li>
                    <a href="?s=studentClasses">
                        Klasy
                    </a>
                </li>
                <li>
                    <a href="?s=account">
                        Moje konto
                    </a>
                </li>
            </ul>
        </nav>
        <nav id="secondaryNav">
            <div>Zalogowano jako <span class="username">{User::loggedIn()->login}</span></div>
            <ul>
                <li>
                    <a href="?s=logout">
                        Wyloguj
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
