<h2>Lista klas</h2>
<a href="?s=studentClasses&do=add" class="button">Dodaj klase</a>
{if $classes}
<div class="shadow">

	<table class="table">
		<thead>
			<tr>
				<th>Nazwa</th>
				<th>Rok</th>
				<th>Symbol</th>
				<th>Wychowawca</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{foreach $classes as $class}
				<tr>
					<td>{$class->nazwa}</td>
					<td>{$class->rok}</td>
					<td>{$class->symbol}</td>
					<td>{$class->leadingTeacher()}</td>
					<td>
						<a href="?s=studentClasses&do=overview&id={$class->id}" class="controls">
							Wyświetl uczniów
						</a>
						<a href="?s=studentClasses&do=edit&id={$class->id}" class="controls">Edytuj</a>
					</td>

				</tr>
			{/foreach}
		</tbody>
	</table>
</div>

{/if}
