<h2>Klasa {$class->symbol}</h2>
<table class="table">
	<tbody>
		<tr>
			<td>Wychowawca</td>
			<td>{$class->leadingTeacher()}</td>
		</tr>
		<tr>
			<td>Rok</td>
			<td>{$class->rok}</td>
		</tr>
		<tr>
			<td>Nazwa</td>
			<td>{$class->nazwa}</td>
		</tr>
		<tr>
			<td>Liczba uczniów</td>
			<td>{count($students)}</td>
		</tr>
	</tbody>
</table>

<div>
	<a href="?s=studentClasses&do=edit&id={$class->id}">Edytuj klase</a>
</div>
<div>
	<a href="?s=studentClasses&id={$class->id}&do=addStudent">Dodaj ucznia</a>
</div>

{if count($students)}
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Imie</th>
				<th>Nazwisko</th>
				<th>PESEL</th>
				<th>Zdjęcie</th>
			</tr>
		</thead>
		<tbody>
			{foreach $students as $student}
				<tr>
					<td>{$student->nr_dziennika}</td>
					<td>
						<a href="?s=studentStats&id=1">{$student->imie}</a>
					</td>
					<td>
						<a href="?s=studentStats&id=1">{$student->nazwisko}</a>
					</td>
					<td>{$student->pesel}</td>
					<td>{$student->photo}</td>
				</tr>
			{/foreach}
		</tbody>
	</table>
{else}
	nie dodano jeszcze uczniów
{/if}
