<h2>Dane ucznia</h2>
<table border="collapse">
	<thead>
		<tr>
			<th colspan="2"><?php echo $student->imie . " " . $student->nazwisko; ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Pesel</td>
			<td><?php echo $student->pesel ?></td>
		</tr>
		<tr>
			<td>Klasa</td>
			<td><?php echo $studentClass->symbol; ?> <?php echo $studentClass->nazwa; ?></td>
		</tr>
		<tr>
			<td>Wychowawca</td>
			<td><?php echo $studentLeader->imie . " " . $studentLeader->nazwisko; ?></td>
		</tr>
	</tbody>
</table>

<h2>Oceny</h2>